/* CVS $Id: $ */
package semanticweb.jena.parsers;

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from /Users/josephcarson/workspace/SemanticWebProjectTest/test/blah_ontology.owl 
 * @author Auto-generated by schemagen on 02 Aug 2015 09:18 
 */
public class BlahPerson {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasFriend = m_model.createObjectProperty( "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#hasFriend" );
    
    public static final DatatypeProperty hasFavoriteFood = m_model.createDatatypeProperty( "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#hasFavoriteFood" );
    
    public static final DatatypeProperty hasFirstName = m_model.createDatatypeProperty( "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#hasFirstName" );
    
    public static final DatatypeProperty hasLastName = m_model.createDatatypeProperty( "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#hasLastName" );
    
    public static final DatatypeProperty worksAt = m_model.createDatatypeProperty( "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#worksAt" );
    
    public static final OntClass BlahPerson = m_model.createClass( "http://www.semanticweb.org/josephcarson/ontologies/2015/6/blah_ontology#BlahPerson" );
    
}
